package us.timandkarli.simpleremote.network.models

import com.tickaroo.tikxml.annotation.PropertyElement
import com.tickaroo.tikxml.annotation.Xml

@Xml(name = "device-info")
data class DeviceInfoResponse(
    @PropertyElement(name = "udn") val udn: String,
    @PropertyElement(name = "serial-number") val serialNumber: String,
    @PropertyElement(name = "device-id") val deviceId: String,
    @PropertyElement(name = "advertising-id") val advertisingId: String,
    @PropertyElement(name = "vendor-name") val vendorName: String,
    @PropertyElement(name = "model-number") val modelNumber: String,
    @PropertyElement(name = "model-name") val modelName: String,
    @PropertyElement(name = "model-region") val modelRegion: String,
    @PropertyElement(name = "is-tv") val isTv: Boolean,
    @PropertyElement(name = "is-stick") val isStick: Boolean,
    @PropertyElement(name = "screen-size") val screenSize: Int,
    @PropertyElement(name = "panel-id") val panelId: String,
    @PropertyElement(name = "tuner-type") val tunerType: String,
    @PropertyElement(name = "supports-ethernet") val supportsEthernet: Boolean,
    @PropertyElement(name = "wifi-mac") val wifiMac: String,
    @PropertyElement(name = "wifi-driver") val wifiDriver: String,
    @PropertyElement(name = "network-type") val networkType: String,
    @PropertyElement(name = "network-name") val networkName: String,
    @PropertyElement(name = "friendly-device-name") val friendlyDeviceName: String,
    @PropertyElement(name = "friendly-model-name") val friendlyModelName: String,
    @PropertyElement(name = "default-device-name") val defaultDeviceName: String,
    @PropertyElement(name = "user-device-name") val userDeviceName: String,
    @PropertyElement(name = "software-version") val softwareVersion: String,
    @PropertyElement(name = "software-build") val softwareBuild: String,
    @PropertyElement(name = "secure-device") val isSecureDevice: Boolean,
    @PropertyElement(name = "language") val language: String,
    @PropertyElement(name = "country") val country: String,
    @PropertyElement(name = "locale") val locale: String,
    @PropertyElement(name = "time-zone-auto") val isTimeZoneAuto: Boolean,
    @PropertyElement(name = "time-zone") val timeZone: String,
    @PropertyElement(name = "time-zone-name") val timeZoneName: String,
    @PropertyElement(name = "time-zone-tz") val timeZoneTz: String,
    @PropertyElement(name = "time-zone-offset") val timeZoneOffset: Int,
    @PropertyElement(name = "clock-format") val clockFormat: String,
    @PropertyElement(name = "uptime") val uptime: Long,
    @PropertyElement(name = "power-mode") val powerMode: String,
    @PropertyElement(name = "supports-suspend") val supportsSuspend: Boolean,
    @PropertyElement(name = "supports-find-remote") val supportsFindRemote: Boolean,
    @PropertyElement(name = "supports-audio-guide") val supportsAudioGuide: Boolean,
    @PropertyElement(name = "supports-rva") val supportsRva: Boolean,
    @PropertyElement(name = "developer-enabled") val isDeveloperModeEnabled: Boolean,
    @PropertyElement(name = "keyed-developer-id") val keyedDeveloperId: String,
    @PropertyElement(name = "search-enabled") val isSearchEnabled: Boolean,
    @PropertyElement(name = "search-channels-enabled") val isSearchChannelsEnabled: Boolean,
    @PropertyElement(name = "voice-search-enabled") val isVoiceSearchEnabled: Boolean,
    @PropertyElement(name = "notifications-enabled") val areNotificationsEnabled: Boolean,
    @PropertyElement(name = "notifications-first-use") val notificationsFirstUse: Boolean,
    @PropertyElement(name = "supports-private-listening") val supportsPrivateListening: Boolean,
    @PropertyElement(name = "supports-private-listening-dtv") val supportsPrivateListeningDtv: Boolean,
    @PropertyElement(name = "supports-warm-standby") val supportsWarmStandby: Boolean,
    @PropertyElement(name = "headphones-connected") val areHeadphonesConnected: Boolean,
    @PropertyElement(name = "supports-ecs-textedit") val supportsEcsTextedit: Boolean,
    @PropertyElement(name = "supports-ecs-microphone") val supportsEcsMicrophone: Boolean,
    @PropertyElement(name = "supports-wake-on-wlan") val supportsWakeOnLan: Boolean,
    @PropertyElement(name = "has-play-on-roku") val hasPlayOnRoku: Boolean,
    @PropertyElement(name = "has-mobile-screensaver") val hasMobileScreensaver: Boolean,
    @PropertyElement(name = "support-url") val supportUrl: String,
    // Added after a Roku update sometime before 4/10/2019
    @PropertyElement(name = "build-number") val buildNumber: String,
    @PropertyElement(name = "grandcentral-version") val grandCentralVersion: String,
    @PropertyElement(name = "trc-version") val trcVersion: String,
    @PropertyElement(name = "trc-channel-version") val trcChannelVersion: String,
    @PropertyElement(name = "davinci-version") val davinciVersion: String
)